### ISSUE TITLE
Example from README: [] replaces a number

### ISSUE THREAD

**Issue by inca** [unclechu/node-deep-extend#17]
I am pretty confused about the logic in README:

  * `f` was `5` initially,
  * `f` is `[]` in extending object,
  * `f` becomes `null` in target object.

Now that's what I call a surprise! Please correct me if I'm wrong to expect `f == []` in target.

TIA

**Comment by unclechu** [comment]
@inca sorry about that, it was documentation issue, `f` was duplicated:
```javascript
var obj2 = {
    b: 3,
    c: 5,
    d: {
        b: { first: 'one', second: 'two' },
        c: { test2: 222 }
    },
    e: { one: 1, two: 2 },
    f: [], // <- here
    g: (void 0),
    h: /abc/g,
    f: null // <- and here
};
```
Actually `f` will be `[]`.

**Comment by inca** [comment]
Got it, thanks!
