### ISSUE TITLE
Why arrays doesn't get merged?

### ISSUE THREAD

**Issue by pateketrueke** [unclechu/node-deep-extend#22]
In your README you point out that extending `j: [1, 2]` with `j: [3, 4]` will return `j: [3,4 ]` and I don't want that behavior... there is an option for concat arrays?

**Comment by unclechu** [comment]
@pateketrueke because it isn't obvious what to do with arrays in this case, concat/replace or something else. There's no way to concat arrays now.

**Comment by shellscape** [comment]
@unclechu resurrecting this one from the dead... it could be possible to create a _factory_ pattern that accepted options for determining behavior. e.g.

```js
const extend = xtend.set({ arrays: 'concat' });
const result = extend({}, {a:[3]}, {a:[1,2]});
// { a: [3, 1, 2] }
```

That could support multiple different methods (which could also be user-extendible), with the default being the current behavior of right-most replacement.
