### ISSUE TITLE
npm6 vulnerability

### ISSUE THREAD

**Issue by caub** [unclechu/node-deep-extend#41]
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack > watchpack > chokidar > fsevents > node-pre-gyp >   │
│               │ rc > deep-extend                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server > chokidar > fsevents > node-pre-gyp > rc │
│               │ > deep-extend                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

Edit: It's fixed in https://github.com/unclechu/node-deep-extend/commit/9423fae877e2ab6b4aecc4db79a0ed63039d4703 and #40

- [x] `rc` got updated: https://github.com/dominictarr/rc/commit/b63377974f60bc5207c15bc8f465e28d2c7e1945
- [ ] `node-pre-gyp` https://github.com/mapbox/node-pre-gyp/pull/379
- [ ]  `fsevents` needs to update `node-pre-gyp`
- [ ]  `chokidar` needs to update `fsevents`
- [ ]  `webpack-dev-server` and `watchpack` needs to update `chokidar`
- [ ]  `webpack` needs to update `watchpack`

**Comment by guylepage3** [comment]
+1. Just ran into this issue.

**Comment by whackdev** [comment]
+1. Encountering same, security report advise update to 0.5.1 or higher will resolve but I still get the same issue.

**Comment by ThLewis** [comment]
+1

**Comment by EmersonCDias** [comment]
Me too. Do we have to wait until someone fix it?

**Comment by KDCinfo** [comment]
Just hit this with my React TypeScript app. Vulnerabilities (80): deep-extend: 11; randomatic: 69
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-scripts-ts [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-scripts-ts > fsevents > node-pre-gyp > rc >            │
│               │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────
```

**Comment by mahdifani14** [comment]
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.5.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > chokidar > fsevents > node-pre-gyp > rc >          │
│               │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by mohsen1** [comment]
This was fixed in #40 

 https://github.com/unclechu/node-deep-extend/commit/9423fae877e2ab6b4aecc4db79a0ed63039d4703#diff-5202fc56f6565a0319e4cbad698a7255

**Comment by rob-orr** [comment]
Ugh.  @unclechu Any idea why this is still showing up as a vulnerability?

**Comment by unclechu** [comment]
@rob-orr No, I don't. I'm actually not very in touch with javascript world these days. So I'd expect someone else to write a test that reproduces it and then I could fix it.

**Comment by guillermodoghel** [comment]
+1

**Comment by unclechu** [comment]
@caub @rob-orr I've tested it by new `npm audit` command and it detected vulnerability in `mocha` package from `devDependencies`, I fixed it and released with `v0.6.0`, so I think it is fixed for now? Could you please check and confirm if it's okay with latest version?

*P.S. As a side-effect I dropped support of older versions of node.js and io.js because they're failing on Travis-CI by those new versions of `devDependencies`.*

**Comment by rob-orr** [comment]
@unclechu Thanks, much appreciated!  We've tested it and it is passing our scanner.  Now we just need `rc` and `closure-loader` to update their dependencies!

**Comment by unclechu** [comment]
@rob-orr Thank you for the response, I'm closing the issue as fixed.
